### ISSUE TITLE
Ignore header files when validating all TagPacks in a path

### ISSUE THREAD

**Issue by behas** [graphsense/graphsense-tagpack-tool#36] opened 2022-08-12 13:32 UTC
It is possible to validate all TagPacks within a given path. However, when the script encounters a header file, which is of course not a valid TagPack, it throws an errors. Possible solution: ignore header files -> possible requires some convention on header file names.

````
tagpack-tool validate packs
= TagPack validation starts ==
Path: packs
Loaded taxonomies: ['entity', 'abuse']
Loaded schema: tagpack_schema.yaml
Collected 3 TagPack files

packs/eth/header.yaml: FAILED
Schema Validation Error: Mandatory header field tags missing
 0/3 TagPacks passed in 0.05s
````

**Comment by behas** [comment] 2022-10-14 08:34
The assumption is that a tagpack directory is structured as follows:

packs
|- header.yaml 
|- BTC
    |- tagpack1.yaml
|- ETH
    |- tagpack2.yaml

If I would like to validate all tagpacks in the nested folders, I run it against the packs folder. But then it also attempts to validate the header.yaml file, which is, of course, not a valid tagpack.

**Comment by mdragaschnig** [comment] 2022-10-17 10:20
> If I would like to validate all tagpacks in the nested folders, I run it against the packs folder. But then it also attempts to validate the header.yaml file, which is, of course, not a valid tagpack.

I cannot reproduce this unfortunately.

Are you referring to a directory structure comparable to [tests/testfiles/yaml_inclusion/](https://github.com/graphsense/graphsense-tagpack-tool/tree/master/tests/testfiles/yaml_inclusion) ?

**Comment by cybersec-code** [comment] 2022-10-19 13:36
This issue is related to support multiple header.yaml files inside a tagpack folder, using a specific structure. The collect_tagpack_files() function currently:
- selects just one among the multiple header.yaml files, with no specific order
- the rest of the header.yaml files are treated as normal tagpacks (thus failing validation)

We could change a bit this function to map each header.yaml file with its tagpacks. For this, we could, for instance, assume:
- header files must be named `header.yaml`
- a header.yaml file will be mapped to all files that are inside sub-directories of the same path (this is, not exactly within the same folder, but at least one folder beyond)

For instance:
```
tp/header.yaml
tp/tagpack_01.yaml    <- This is not mapped to any header
tp/subfolder_01/tagpack_02.yaml    <- This is mapped to tp/header.yaml
tp/subfolder_01/subfolder_02/header.yaml
tp/subfolder_01/subfolder_02/subfolder_03/tagpack_03.yaml    <- This is mapped to tp/subfolder_01/subfolder_02/header.yaml
```

So if tagpack_02.yaml and tagpack_03.yaml use the directive `include: !header.yaml`, the right header will be included (the closest in a parent folder).

See PR #54

**Comment by behas** [comment] 2022-10-20 06:23
To me that makes sense, especially if header files can include other header files. In that way, we can arrange tags by category / currency etc, and avoid repetition of common header fields (e.g., title).

**Closed** 2022-10-28 12:32 UTC
Labels: enhancement
